import type { Metadata } from "next";

import "./globals.css";

// import { Gi } from "next/font/google";

// const roboto = Gibson({
// 	subsets: ["latin"],
// 	weight: ["100", "300", "500", "700", "900"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased min-h-screen h-fit`}>{children}</body>
    </html>
  );
}
